disasterinfosite/urls.py
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.gis import admin
from django.conf import settings
from django.views.i18n import JavaScriptCatalog

from disasterinfosite import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),

    # API urls
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/create_user/', views.create_user, name="create_user"),

    # Our own user account actions
    path('accounts/update_profile/',
         views.update_profile, name="update_profile"),
    path('accounts/update_prepare_action/',
         views.prepare_action_update, name='prepare_action_update')
]

# user-facing URLs
urlpatterns += i18n_patterns(path('', views.app_view, name='index'))
urlpatterns += i18n_patterns(path('about/', views.about_view, name='about'))
urlpatterns += i18n_patterns(path('prepare/',
                                  views.prepare_view, name='prepare'))
urlpatterns += i18n_patterns(path('data/', views.data_view, name='data'))

# enable translations in javascript
urlpatterns += i18n_patterns(path("jsi18n/", JavaScriptCatalog.as_view(),
                                  name="javascript-catalog"))


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

disasterinfosite/models.py
from collections import OrderedDict
from django.contrib.auth.models import User
from django.contrib.gis.db import models
from django.contrib.gis.gdal import OGRGeometry
from django.contrib.gis.geos import Point
from django.contrib.gis.db.models import Extent
from embed_video.fields import EmbedVideoField
from model_utils.managers import InheritanceManager
from solo.models import SingletonModel
from django.core.files.storage import FileSystemStorage
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.contrib.postgres.validators import (
    RangeMinValueValidator, RangeMaxValueValidator)


SNUG_TEXT = 0
SNUG_VIDEO = 1
SNUG_SLIDESHOW = 2

SNUGGET_TYPES = (
    ('SNUG_TEXT', 'TextSnugget'),
    ('SNUG_VIDEO', 'EmbedSnugget'),
    ('SNUG_SLIDESHOW', 'SlideshowSnugget')
)


class PreparednessAction(models.Model):
    title = models.TextField(default="")
    image = models.ImageField(upload_to="prepare_images")
    cost = models.IntegerField(default=0,
                               validators=[
                                   RangeMinValueValidator(0),
                                   RangeMaxValueValidator(4)
                               ])
    happy_text = models.TextField(default="")
    useful_text = models.TextField(default="")
    property_text = models.TextField(default="")
    content_text = models.TextField(default="")
    link_icon = models.ImageField(upload_to="prepare_images")
    slug = models.TextField(default="")

    def __str__(self):
        return self.title


class PreparednessLink(models.Model):
    text = models.TextField(default="")
    url = models.URLField(default="")
    action = models.ForeignKey(PreparednessAction, on_delete=models.CASCADE)

    def __str__(self):
        return self.text + "(" + self.url + ") action: " + self.action


class UserProfile(models.Model):
    """ A model representing a user's information that isn't their
    username, password, or email address """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address1 = models.CharField(max_length=200, blank=True)
    address2 = models.CharField(max_length=200, blank=True)
    city = models.CharField(max_length=200, blank=True)
    state = models.CharField(max_length=50, blank=True)
    zip_code = models.CharField(max_length=50, blank=True)
    actions_taken = models.ManyToManyField(PreparednessAction, blank=True)

    class Meta:
        verbose_name = "User Profile"

    def __str__(self):
        return "{0}: {1}, {2} {3}, {4} {5}: {6}".format(
            self.user,
            self.address1,
            self.address2,
            self.city,
            self.state,
            self.zip_code,
            self.actions_taken.all().values_list('title', flat=True)
        )


class SiteSettings(SingletonModel):
    """A singleton model to represent site-wide settings."""
    area_name = models.CharField(
        max_length=100,
        default="the affected area",
        help_text="Describe the entire area that this app covers, e.g. 'Oregon' or 'Missoula County'."  # noqa: ES501
    )
    about_text = models.TextField(
        default="Information about your organization goes here.",
        help_text="Describe the data and the agencies that it came from."
    )
    contact_email = models.EmailField(
        blank=True,
        help_text="Put a contact email for the maintainer of this site here."
    )
    site_url = models.URLField(
        default="https://www.example.com",
        help_text="Put the URL to this site here."
    )
    site_title = models.CharField(
        max_length=50,
        default="Your Title Here!"
    )
    site_description = models.CharField(
        max_length=200,
        default="A disaster preparedness website",
        help_text="A small, catchy description for this site."
    )
    intro_text = models.TextField(
        default="A natural disaster could strike your area at any time.",
        help_text="A description of what we are trying to help people prepare for, or the goal of your site."  # noqa: ES501
    )
    who_made_this = models.TextField(
        default="Information about the creators and maintainers of this particular site.",  # noqa: ES501
        help_text="Include information about who you are and how to contact you."  # noqa: ES501
    )
    data_download = models.URLField(
        blank=True,
        help_text="A link where people can download a zipfile of all the data that powers this site."  # noqa: ES501
    )

    def __unicode__(self):
        return u"Site Settings"

    class Meta:
        verbose_name = "Site Settings"


class Location(SingletonModel):
    """A singleton model to represent the location
    covered by this website's data"""

    def __unicode__(self):
        return u"Location Information"

    @staticmethod
    def get_data_bounds():
        bounds = {
            ######################################################
            # GENERATED CODE GOES HERE
            # DO NOT MANUALLY EDIT CODE IN THIS SECTION- IT WILL BE OVERWRITTEN
            # locationsList
            # END OF GENERATED CODE BLOCK
            ######################################################
        }

        # The smallest/largest possible values, as appropriate, so the map will display
        # something if there is no data
        north = [-80]
        west = [180]
        south = [80]
        east = [-180]

        for box in bounds.values():
            if box is not None:
                west.append(box[0])
                south.append(box[1])
                east.append(box[2])
                north.append(box[3])

        # The largest box that contains all the bounding boxes,
        # how Leaflet wants it.
        return [[min(south), min(west)], [max(north), max(east)]]

    class Meta:
        verbose_name = "Location Information"


class ShapeManager(models.Manager):
    def data_bounds(self):
        return self.aggregate(Extent('geom'))['geom__extent']


class RasterManager(models.Manager):
    def data_bounds(self):
        return self.aggregate(Extent('bbox'))['bbox__extent']


class ShapefileGroup(models.Model):
    name = models.CharField(max_length=50)
    display_name = models.CharField(max_length=50, default="")
    order_of_appearance = models.IntegerField(
        default=0,
        help_text="The order, from top to bottom, in which you would like this group to appear, when applicable."  # noqa: ES501
    )
    note = models.TextField(
        blank=True,
        help_text='A note that appears above all snuggets in this section. Use for data caveats or warnings.'  # noqa: ES501
    )

    def __str__(self):
        return self.name

######################################################
# GENERATED CODE GOES HERE
# DO NOT MANUALLY EDIT CODE IN THIS SECTION - IT WILL BE OVERWRITTEN
# modelsClasses
# END OF GENERATED CODE BLOCK
######################################################


class SnuggetType(models.Model):
    name = models.CharField(max_length=50)
    model_name = models.CharField(max_length=255, choices=SNUGGET_TYPES)

    def __str__(self):
        return self.name


class SnuggetSection(models.Model):
    name = models.CharField(max_length=100)
    display_name = models.CharField(
        max_length=100,
        help_text="The name to show for this section",
        default=""
    )
    collapsible = models.BooleanField(
        default=True,
        help_text='Whether this section of the data is collapsible'
    )
    order_of_appearance = models.IntegerField(
        default=0,
        help_text="The order in which you'd like this to appear in the tab. 0 is at the top."  # noqa: ES501
    )

    def __str__(self):
        return self.name


class SnuggetPopOut(models.Model):
    text = models.TextField(default='')
    image = models.ImageField(upload_to="popout_images")
    link = models.TextField(default='', max_length=255)
    alt_text = models.TextField(default='', max_length=255)
    video = EmbedVideoField(null=True)

    @property
    def has_content(self):
        "Returns true if this popout has some content"
        return (self.text or self.image or self.link or self.video)

    def __str__(self):
        return self.text[:100]


@receiver(pre_save, sender=SnuggetSection)
@receiver(pre_save, sender=ShapefileGroup)
def default_display_name(sender, instance, *args, **kwargs):
    if not instance.display_name:
        instance.display_name = instance.name


"""
looks up a point in a set of rasters and returns the first non-NODATA value it finds
 or None if there are no rasters, the point is not within any of them or it's in a NODATA pixel.
 raster algebra taken from the django-raster project version 0.6 at
 https://github.com/geodesign/django-raster/blob/master/raster/utils.py
 """


def rasterPointLookup(rasterCollection, lng, lat, band=0):
    # if we have no data at all, then save time and return None immediately
    sampleBBOX = rasterCollection.objects.only("bbox").first().bbox
    if sampleBBOX is None:
        return None

    rasterPoint = OGRGeometry(
        'POINT({0} {1})'.format(lng, lat), srs=sampleBBOX.srs)
    vectorPoint = Point(lng, lat, srid=sampleBBOX.srid)

    """ Using the filter here lets PostGIS do an indexed search on the bbox
    field, which is much faster than stepping through the objects.
    Note that it will almost always only return one raster, but there could
    theoretically be 2 or 4 if our point is perfectly on a tile boundary.
    In that instance, we return the first non-NODATA value we find.
    """
    for tile in rasterCollection.objects.filter(
            bbox__contains=vectorPoint).all():
        # only bother to check for data if we're within the bounds
        rst = tile.rast
        offset = (
            abs(rst.origin.x - rasterPoint.coords[0]),
            abs(rst.origin.y - rasterPoint.coords[1])
        )
        offset_idx = [int(offset[0] / abs(rst.scale.x)),

disasterinfosite/templates/about.html
{% load js %}
{% load i18n %}

{% load render_bundle from webpack_loader %}
{% load webpack_static from webpack_loader %}

{% get_current_language as LANGUAGE_CODE %}
{% get_current_language_bidi as LANGUAGE_BIDI %}

<!DOCTYPE html>
<html class="no-js" lang="{{ LANGUAGE_CODE }}" dir="{% if LANGUAGE_BIDI %}rtl{% else %}ltr{% endif %}">
{% include "head-meta.html" with file="about" %}

<body>
{% include "simple-header.html" %}

  <div class="content-container">
    <div class="about-container">
      <h3 class="caps">{% trans "The Hazard Ready Team" %}</h3>
      <div class="bio-container">
        <div class="bio bio--carson">
          <div class="bio__image">
            <img src="{% webpack_static 'build/cmk_headshot.jpg' %}" alt="">
          </div>
          <div class="bio__other">
            <div class="bio__text">
              <h4 class="bio__name h4--sans-serif">Carson MacPherson-Krutsky</h4>
              <p>
                {% trans "Carson MacPherson-Krutsky holds a Ph.D. in geosciences from Boise State University and is a research associate at the Natural Hazards Center at the University of Colorado Boulder. Her work centers on effective risk communication for diverse audiences and bridging disciplines to aid real-world decision-making. She oversees and develops content for HazardReady websites, which originated from her master’s research at the University of Montana." %}
              </p>
              <p class="bio__links">
                <a href="https://www.linkedin.com/in/carsonmk/" target="_blank" rel="noopener"><img src="{% webpack_static 'build/linkedin-logo.png' %}" alt="" class="linkedin-logo"><span class="sr-only">LinkedIn Profile</span></a> <a href="https://sites.google.com/view/carsonmk/about" target="_blank" rel="noopener"><img class="link-icon" src="{% webpack_static 'build/about-link.svg' %}" alt=""><span class="sr-only">personal website</span></a>
              </p>
            </div>
            </div>
          </div>
          <div class="bio bio--becks">
            <div class="bio__image">
              <img src="{% webpack_static 'build/rbk_headshot.jpg' %}" alt="">
            </div>
            <div class="bio__other bio__other--reverse">
              <div class="bio__text">
                <h4 class="bio__name h4--sans-serif">Rebecca Bendick</h4>
                <p>
                  {% trans "Rebecca Bendick has a Ph.D. in geophysics from the University of Colorado. Her research on tectonics and earthquake mechanics led to an interest in how human communities are affected by natural disasters, and inspires her ongoing efforts to help people better understand and prepare for them. She writes and lectures on the ethics of science communication as well as on her basic geophysical research." %}
                </p>
                <p class="bio__links">
                  <a href="https://hs.umt.edu/geosciences/faculty/bendick/" target="_blank" rel="noopener"><img class="link-icon" src="{% webpack_static 'build/about-link.svg' %}" alt=""><span class="sr-only">personal website</span></a>
                </p>
              </div>
            </div>
          </div>
          <div class="bio bio--grant">
            <div class="bio__image">
              <img src="{% webpack_static 'build/gk_headshot.jpg' %}" alt="">
            </div>
            <div class="bio__other">
              <div class="bio__text">
                <h4 class="bio__name h4--sans-serif">Grant Kier</h4>
                <p>
                  {% trans "Grant Kier has a M.Sc. in geology from the University of Colorado. He is broadly interested in community resilience in the context of manmade and natural changes. He also has a background in business practices and currently works on economic development, fostering small and startup companies in western Montana." %}
                </p>
              </div>
            </div>
          </div>
          <div class="bio bio--melinda">
            <div class="bio__image">
              <img src="{% webpack_static 'build/mm_headshot.jpg' %}" alt="">
            </div>
            <div class="bio__other bio__other--reverse">
              <div class="bio__text">
                <h4 class="bio__name h4--sans-serif">Melinda Minch</h4>
                <p>
                  {% trans "Melinda Minch has a M.Sc. in Computer Science from Case Western Reserve University. She is a freelance software developer who prefers to work on projects that contribute positively to society; her favorite projects involve working with scientists and researchers to make websites that further their goals." %}
                </p>
                <p class="bio__links">
                  <a href="https://melindaminch.com" target="_blank" rel="noopener"><img class="link-icon" src="{% webpack_static 'build/about-link.svg' %}" alt=""><span class="sr-only">personal website</span></a>
                </p>
              </div>
            </div>
          </div>
          <div class="bio bio--courtenay">
            <div class="bio__image">
              <img src="{% webpack_static 'build/cd_headshot.jpg' %}" alt="">
            </div>
            <div class="bio__other">
              <div class="bio__text">
                <h4 class="bio__name h4--sans-serif">Courtenay Duzet</h4>
                <p>
                  {% trans "Courtenay Duzet has a B.Sc. in Environmental Sciences from Oregon State University and an M.Sc. in Geosciences from the University of Montana. She currently works as a data manager and science communicator for the U.S. Geological Survey's National Climate Adaptation Science Center. " %}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="about-container about-container--hazardready">
        <h3 class="caps about--hazardready">{% trans "The Hazard Ready Project" %}</h3>
        <div class="hazardready-container">
          <a href="https://hazardready.org" target="_blank" rel="noopener">
            <img class="hazardready-logo" src="{% webpack_static 'build/logo.png' %}" alt=""><span class="sr-only">{% trans "Hazard Ready homepage" %}</span></a>
          <p>{{ settings.about_text | safe }}</p>
        </div>
      </div>
      <div class="about-container">
        {{ settings.about_text | safe }}
      </div>
      <div class="about-container">
        <div class="about-content__text">
          <p>
              {% blocktrans with title=settings.site_title area_name=settings.area_name %}{{ title }} is designed to help educate and prepare people for disasters that occur in their area. Disasters don’t strike locations equally so we found it important to give location specific information in order to properly prepare. {{ title }} organizes current information and packages it in a way that makes it accessible for any {{ area_name }} resident.{% endblocktrans %}
          </p>
          <p>
              {% blocktrans with area_name=settings.area_name %}This site uses the most up-to-date hazard risk data available for {{ area_name }}. The user of this site is responsible for verifying any particular information with the original data sources. Although these data represent the best current assessment of hazards, they are not predictive of future events. The descriptions of risk and how to prepare for those risks are based on best information from the American Red Cross and the Federal Emergency Management Agency.{% endblocktrans %}
          </p>
        </div>
        <div class="about-content__flowchart">
          {% trans 'build/flowchart.jpg' as flowchart %}
          <img src="{% webpack_static flowchart %}" alt="">
          <p class="sr-only">
            {% blocktrans %}How we build Hazard Ready Sites: 1. Gather data. Locate the most relevant and up-to-date data on natural hazards for your region from trusted sources like FEMA, NOAA, and the USGS. 2. Quality Check. Work with local partners (community groups & emergency managers) to ensure the data and infomration are accurate. 3. Process data. Make the data compatible with Hazard Ready software. 4. Build content. Write the webpage text, gather images and videos, locate local resources for each hazard and region. 5. Feedback and focus groups. Discuss content and designs to ensure the information fits each community's needs. 6. Revise, revise, revise and launch site!{% endblocktrans %}
          </p>
        </div>
      </div>
      {% if settings.data_download %}
        <div class="about-container">

          <p>
              {% blocktrans with title=settings.site_title download=settings.data_download%}Data used for {{ title }} is available for download <a href="{{ download }}" target="_blank" rel="noopener">here</a>.{% endblocktrans %}
          </p>
        </div>
      {% endif %}
  </div>

{% include "geek_box.html" %}
{% include "page-end-meta.html" with file="about" %}

</body>
</html>

disasterinfosite/templates/data.html
{% load js %}
{% load i18n %}

{% load render_bundle from webpack_loader %}
{% load webpack_static from webpack_loader %}

{% get_current_language as LANGUAGE_CODE %}
{% get_current_language_bidi as LANGUAGE_BIDI %}

<!DOCTYPE html>
<html class="no-js" lang="{{ LANGUAGE_CODE }}" dir="{% if LANGUAGE_BIDI %}rtl{% else %}ltr{% endif %}">
{% include "head-meta.html" with file="data" %}

<body>
{% include "simple-header.html" %}
  <div class="content-container">
    <h2>{% trans "Data overview images for Hazard Ready" %}</h2>
    <div class="data__list">
      {% for item in quick_data_overview %}
        <div class="data__image">
          <a target="_blank" rel="noopener" href="{{ item.pdf.url }}">
            {{ item.link_text }}
            <img class="data__thumbnail" src="{{ item }}" alt="{% trans 'A map of the affected area, indicating hazard intensity' %}">
          </a>
        </div>
      {% endfor %}
    </div>
  </div>
{% include "geek_box.html" %}
{% include "page-end-meta.html" with file="data" %}

</body>
</html>

disasterinfosite/templates/geek_box.html
{% load i18n %}
{% load webpack_static from webpack_loader %}

<div role="contentinfo" id="geek-box">
    <a href="https://hazardready.org" target="_blank" rel="noopener" class="geek-box-logo"><img src="{% webpack_static 'build/logo.png' %}" alt=""><span class="sr-only">Hazard Ready homepage</span></a>
    <div class="geek-text">
        <h3>{% trans "Who made this?" %}</h3>
        {% url 'about' as about_url %}
        <p>
        {% if settings.contact_email %}
            {% blocktrans with email=settings.contact_email %}
                Have questions? View the <a href="{{ about_url }}" target="_blank">About</a> page or <a href="mailto:{{ email }}">email the Hazard Ready creators</a> for more information.
            {% endblocktrans %}
        {% else %}
            {% blocktrans %}Have questions? View the <a href="{{ about_url }}" target="_blank">About</a> page for more information."{% endblocktrans %}
        {% endif %}
        </p>
    </div>
</div>

disasterinfosite/templates/header_links.html
{% load i18n %}

<a class="link--plain" href="{% url 'about' %}">
  <h5 class="about__link link--grey" role="navigation">{% trans "About" %}</h5>
</a>
<a class="link--plain" href="{% url 'data' %}">
  <h5 class="about__link link--grey" role="navigation">{% trans "Data" %}</h5>
</a>

disasterinfosite/templates/prepare-header.html
{% extends "header.html" %}
{% load i18n %}

{% block search %}{% endblock search %}

disasterinfosite/templates/prepare.html
{% load js %}
{% load i18n %}
{% load show_cost %}
{% load show_cost_header %}

{% load render_bundle from webpack_loader %}
{% load webpack_static from webpack_loader %}

{% get_current_language as LANGUAGE_CODE %}
{% get_current_language_bidi as LANGUAGE_BIDI %}

<!DOCTYPE html>
<html class="no-js" lang="{{ LANGUAGE_CODE }}" dir="{% if LANGUAGE_BIDI %}rtl{% else %}ltr{% endif %}">
  {% include "head-meta.html" with file="prepare" %}

  <body>
    {% include "prepare-header.html" %}
    <div class="content-container">
      <div class="prepare-hero" style="background-image: url({% webpack_static 'build/basic_kit.jpg' %})">
        <div class="overlay">
          <h1 class="h1-sans-serif hero__text">{% trans 'Take the first step toward getting prepared' %}</h1>
        </div>
      </div>
      <p class="prepare-intro">{% trans "There are a few simple steps we can take to make our families and community more prepared for emergencies. It doesn't have to be expensive or difficult. You may have already done some of it! You can use the checklist at the bottom of this page to keep track of how much you've done." %}</p>
      <div class="prepare-container">
        <div class="prepare-actions">
          {% regroup actions by cost as actions_by_cost %}
          {% for cost, items in actions_by_cost %}
            <h4 class="section-title section-title--collapse" data-section="cost--{{cost}}" role="button">
              <img class="caret{% if forloop.first %} caret--up{% endif %}" src="{% webpack_static 'build/caret.svg' %}" alt=""/>
              {{ cost | show_cost_header }}
            </h4>
            <div class="{% if forloop.first %}section-content{% else %}section-content section-content--collapse{% endif %} prepare-content" id="cost--{{cost}}">
                <ul class="prepare-content__list">
                  {% for item in items %}
                    <li class="prepare-content__item{% if forloop.first %} prepare-content__item--active{% endif %}" role="button" aria-controls="{{ item.slug }}" data-item="{{ item.slug }}" id="{{ item.slug }}-control">{{ item.title }}</li>
                  {% endfor %}
                </ul>
            </div>
          {% endfor %}
        </div>
        <div class="prepare-detail">
          {% for item in actions %}
            <div class="{% if forloop.first %}prepare-item{% else %}prepare-item hide{% endif %}" id="{{ item.slug }}" data-section="cost--{{item.cost}}" role="region"  aria-labelledby="{{ item.slug }}-control">
              {% if item.image %}
                <img class="prepare-item__image" alt="" src="{{ item.image.url }}">
              {% endif %}

              <h3 class="h3--sans-serif">{{ item.title }}</h3>

              {{ item.content_text | safe }}

              {% if item.happy_text %}
              <p>
                <img class="prepare__icon" src="{% webpack_static 'build/icon-happy.svg' %}" alt=""> {{ item.happy_text }}
              </p>
              {% endif %}
              {% if item.useful_text %}
              <p>
                <img class="prepare__icon" src="{% webpack_static 'build/icon-useful.svg' %}" alt=""> {{ item.useful_text }}
              </p>
              {% endif %}
              {% if item.property_text %}
              <p>
                <img class="prepare__icon" src="{% webpack_static 'build/icon-home.svg' %}" alt=""> {{ item.property_text }}
              </p>
              {% endif %}
              {% with links=item.preparednesslink_set.all %}
                  {% for link in links %}
                    <div class="prepare-item__link">
                      <a href="{{ link.url }}" target="_blank" rel="noopener">
                        {% if item.link_icon %}
                          <img class="prepare-item__link-icon" alt="" src="{{ link.url }}">
                        {% endif %}
                        {% if link.text %}
                          {{ link.text }}
                        {% endif %}
                      </a>
                    </div>
                  {% endfor %}
              {% endwith %}
            </div>
          {% endfor %}
        </div>
      </div>

      <div class="print-container">
        <div class="print-header">
          <div class="print-header__activity">{% trans 'This activity' %}&hellip;</div>
          <div class="print-button"><img class="prepare__icon" src="{% webpack_static 'build/icon-print.svg' %}" alt=""> {% trans 'Print Checklist' %}</div>
        </div>
        <table class="print-table">
          <tr>
            <th class="center-align">{% trans 'Completed?' %}</th>
            <th>{% trans 'Activity' %}</th>
            <th class="center-align">&hellip;{% trans 'reduces emotional and physical harm' %}<br><img class="print-table__icon" src="{% webpack_static 'build/icon-happy.svg' %}" alt="">
            </th>
            <th class="center-align">&hellip;{% trans 'is useful for other situations' %}<br><img class="print-table__icon" src="{% webpack_static 'build/icon-useful.svg' %}" alt="">
            </th>
            <th class="center-align">&hellip;{% trans 'helps protect property' %}<br><img class="print-table__icon" src="{% webpack_static 'build/icon-home.svg' %}" alt="">
            </th>
            <th class="center-align">&hellip;{% trans 'costs' %}<br><img class="print-table__icon" src="{% webpack_static 'build/icon-money.svg' %}" alt="">
            </th>
            <th class="resources">{% trans 'Resources' %}
          </tr>
          {% for item in actions %}
            <tr>
              <td class="center-align">
                <input type="checkbox" aria-label="completed" class="checkbox--action-taken" value="{{ item.id }}" {% if item.id in actions_taken %}checked{% endif %}>
              </td>
              <td>{{ item.title }}</td>
              <td class="center-align">{% if item.happy_text %}<img class="print-table__icon" src="{% webpack_static 'build/icon-check.svg' %}" alt="{% trans 'reduces emotional and physical harm' %}">{% endif %}
              </td>
              <td class="center-align">{% if item.useful_text %}<img class="print-table__icon" src="{% webpack_static 'build/icon-check.svg' %}" alt="{% trans 'is useful for other situations' %}">{% endif %}
              </td>
              <td class="center-align">{% if item.property_text %}<img class="print-table__icon" src="{% webpack_static 'build/icon-check.svg' %}" alt="{% trans 'helps protect property' %}">{% endif %}
              </td>
              <td class="center-align">{{ item.cost | show_cost }}</td>
              <td class="resources">
                {% with links=item.preparednesslink_set.all %}
                  <ul>
                  {% for link in links %}
                    <li>
                      <a href="{{ link.url }}" target="_blank" rel="noopener">
                        {% if item.link_icon %}
                          <img class="prepare-item__link-icon" alt="" src="{{ link.url }}">
                        {% endif %}
                        {% if link.text %}
                          {{ link.text }}
                        {% endif %}
                      </a>
                    </li>
                  {% endfor %}
                  </ul>
                {% endwith %}
              </td>
            </tr>
          {% endfor %}
        </table>
        <div class="print-footer">
          <div class="print-key">
            {% trans 'Key:' %} $ = $1 - $30
          </div>
          <div class="print-key">
            $$ = $31 - $100
          </div>
          <div class="print-key">
            $$$ = $101 - $300
          </div>
          <div class="print-key">
            $$$$ = $301 {% trans 'or more' %}
          </div>
        </div>
      </div>
    </div>
    {% include "geek_box.html" %}
    <script type="text/javascript">
      var loggedIn = {{ logged_in | js }};
    </script>
    {% include "page-end-meta.html" with file="prepare" %}

  </body>
</html>

disasterinfosite/templates/simple-header.html
{% extends "header.html" %}
{% load i18n %}

{% block links-small %}{% endblock links-small %}
{% block search %}{% endblock search %}
{% block links-med-and-up %}{% endblock links-med-and-up %}

disasterinfosite/templates/snugget_slideshow.html
{% load i18n %}

{% block snugget-content %}
  <div class="snugget">
    {{ snugget.text | safe }}
  </div>

  <!-- see pop_out.html for slideshow. It could go here too. -->
{% endblock %}